//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CM.Shared.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationMeta
    {
        public System.Guid LocationID { get; set; }
        public string LocationCreateDate { get; set; }
        public string LocationAuthorID { get; set; }
        public string LocationRowVersion { get; set; }
    }
}
