//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CM.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessMeta
    {
        public System.Guid BusinessContactID { get; set; }
        public string BusinessMetaCreateDate { get; set; }
        public string BusinessMetaAuthorID { get; set; }
        public string BusinessMetaRowVersion { get; set; }
    }
}
