//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CM.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessContact : BusinessMeta
    {
        public string BCGivenName { get; set; }
        public string BCSurName { get; set; }
        public string BCEmail { get; set; }
        public string BCPhone { get; set; }
        public string BCWebsite { get; set; }
        public System.Guid ClientClientID { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
