//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CM.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientMeta
    {
        public System.Guid ClientID { get; set; }
        public long ClientCreateDate { get; set; }
        public string ClientAuthorID { get; set; }
        public long ClientRowVersion { get; set; }
    }
}
