//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CM.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location : LocationMeta
    {
        public string LocationName { get; set; }
        public string LocationAddress { get; set; }
        public string LocationZip { get; set; }
        public string LocationCountry { get; set; }
        public string LocationPhone { get; set; }
        public string LocationWebsite { get; set; }
        public string LocationImageFileName { get; set; }
        public string LocationLat { get; set; }
        public string LocationLong { get; set; }
    
        public virtual LocationType LocationType { get; set; }
    }
}
