//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CM.DAL.DataManager
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Data.Entity;
    using System.Linq;
    using CM.Interfaces;
    using CM.Shared.Entities;
    using CM.DAL.EntityModel;
    public partial class BusinessMetaManager : IDataManager
    {
        private FCDB DB;
              
        public BusinessMetaManager()
        {
            DB = new FCDB();
        }
    
        /// <summary>
        /// Adds an BusinessMeta object to the DbSet of BusinessMetas
        /// </summary>
        /// <typeparam name="BusinessMeta">The BusinessMeta to be added.</param>
        protected virtual void _Add(BusinessMeta obj) {
    
                DB.BusinessMetas.Add(obj); 
                DB.SaveChanges();
            
        }
    
        /// <summary>
        /// Updates an BusinessMeta object to the DbSet of BusinessMetas
        /// </summary>
        /// <typeparam name="BusinessMeta">The BusinessMeta to be updated.</param>
        protected virtual void _Update(BusinessMeta obj) {
    
                DB.Entry<BusinessMeta>(obj).State = EntityState.Modified;
                DB.SaveChanges();
            
        }
        
        /// <summary>
        /// Deletes an BusinessMeta object to the DbSet of BusinessMetas
        /// </summary>
        /// <typeparam name="BusinessMeta">The BusinessMeta to be deleted.</param>
        protected virtual void _Delete(BusinessMeta obj) {
    
                DB.Entry<BusinessMeta>(obj).State = EntityState.Deleted;
                DB.SaveChanges();
            
        }
        
        /// <summary>
        /// Get an list of BusinessMetas
        /// </summary>
        /// <returns>List of BusinessMetas</returns>
        protected virtual IEnumerable<BusinessMeta> _GetList() {
            return DB.BusinessMetas.Select(s=>s);
        }
    
        /// <summary>
        /// Detaches an BusinessMeta object from the object state manager.
        /// </summary>
        /// <typeparam name="BusinessMeta">The BusinessMeta to be detached.</param>
        public virtual void Detach(Object obj) 
    	{
            DB.Entry<BusinessMeta>((BusinessMeta)obj).State = EntityState.Detached;
            DB.SaveChanges();   
        }
        
        /// <summary>
        /// Adds an BusinessMeta object to the DbSet of BusinessMetas
        /// </summary>
        /// <typeparam name="BusinessMeta">The BusinessMeta to be added.</param>
        public virtual void Add(Object obj) 
    	{
            _Add((BusinessMeta)obj);
        }
    
        /// <summary>
        /// Updates an BusinessMeta object to the DbSet of BusinessMetas
        /// </summary>
        /// <typeparam name="BusinessMeta">The BusinessMeta to be updated.</param>
        public virtual void Update(Object obj) 
    	{
            _Update((BusinessMeta)obj);
        }
        
        /// <summary>
        /// Deletes an BusinessMeta object to the DbSet of BusinessMetas
        /// </summary>
        /// <typeparam name="BusinessMeta">The BusinessMeta to be deleted.</param>
        public virtual void Delete(Object obj) 
    	{
            _Delete((BusinessMeta)obj);
        }
        
        /// <summary>
        /// Get an list of BusinessMetas
        /// </summary>
        /// <returns>List of BusinessMetas</returns>
        public virtual IEnumerable<BusinessMeta> GetList() 
    	{
            return _GetList();
        }
        
    
        /// <summary>
        /// Gets single an BusinessMeta object by an key object, key property is (BusinessContactID)
        /// </summary>
        /// <typeparam name="BusinessMeta">The BusinessMeta to be added.</param>
        /// <returns>An single BusinessMeta object</returns>
        public virtual BusinessMeta GetByBusinessContactID(System.Guid businesscontactid) 
    	{
            if(DB.BusinessMetas.Select(s=>s).Where(w=>w.BusinessContactID == businesscontactid).Any()) 
    		{
                return DB.BusinessMetas.Select(s=>s).Where(w=>w.BusinessContactID == businesscontactid).FirstOrDefault();
            } else {
                return null;
            }
        }
    
                    
    }
}
