//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CM.DAL.DataManager
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Data.Entity;
    using System.Linq;
    using CM.Interfaces;
    using CM.Shared.Entities;
    using CM.DAL.EntityModel;
    public partial class BusinessContact : BusinessMetaManager : IDataManager
    {
        private FCDB DB;
              
        public BusinessContactManager()
        {
            DB = new FCDB();
        }
    
        /// <summary>
        /// Adds an BusinessContact object to the DbSet of BusinessContacts
        /// </summary>
        /// <typeparam name="BusinessContact">The BusinessContact to be added.</param>
        protected virtual void _Add(BusinessContact obj) {
    
                DB.BusinessContacts.Add(obj); 
                DB.SaveChanges();
            
        }
    
        /// <summary>
        /// Updates an BusinessContact object to the DbSet of BusinessContacts
        /// </summary>
        /// <typeparam name="BusinessContact">The BusinessContact to be updated.</param>
        protected virtual void _Update(BusinessContact obj) {
    
                DB.Entry<BusinessContact>(obj).State = EntityState.Modified;
                DB.SaveChanges();
            
        }
        
        /// <summary>
        /// Deletes an BusinessContact object to the DbSet of BusinessContacts
        /// </summary>
        /// <typeparam name="BusinessContact">The BusinessContact to be deleted.</param>
        protected virtual void _Delete(BusinessContact obj) {
    
                DB.Entry<BusinessContact>(obj).State = EntityState.Deleted;
                DB.SaveChanges();
            
        }
        
        /// <summary>
        /// Get an list of BusinessContacts
        /// </summary>
        /// <returns>List of BusinessContacts</returns>
        protected virtual IEnumerable<BusinessContact> _GetList() {
            return DB.BusinessContacts.Select(s=>s);
        }
    
        /// <summary>
        /// Detaches an BusinessContact object from the object state manager.
        /// </summary>
        /// <typeparam name="BusinessContact">The BusinessContact to be detached.</param>
        public virtual void Detach(Object obj) 
    	{
            DB.Entry<BusinessContact>((BusinessContact)obj).State = EntityState.Detached;
            DB.SaveChanges();   
        }
        
        /// <summary>
        /// Adds an BusinessContact object to the DbSet of BusinessContacts
        /// </summary>
        /// <typeparam name="BusinessContact">The BusinessContact to be added.</param>
        public virtual void Add(Object obj) 
    	{
            _Add((BusinessContact)obj);
        }
    
        /// <summary>
        /// Updates an BusinessContact object to the DbSet of BusinessContacts
        /// </summary>
        /// <typeparam name="BusinessContact">The BusinessContact to be updated.</param>
        public virtual void Update(Object obj) 
    	{
            _Update((BusinessContact)obj);
        }
        
        /// <summary>
        /// Deletes an BusinessContact object to the DbSet of BusinessContacts
        /// </summary>
        /// <typeparam name="BusinessContact">The BusinessContact to be deleted.</param>
        public virtual void Delete(Object obj) 
    	{
            _Delete((BusinessContact)obj);
        }
        
        /// <summary>
        /// Get an list of BusinessContacts
        /// </summary>
        /// <returns>List of BusinessContacts</returns>
        public virtual IEnumerable<BusinessContact> GetList() 
    	{
            return _GetList();
        }
        
    
    }
}
