//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CM.DAL.DataManager
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Data.Entity;
    using System.Linq;
    using CM.Interfaces;
    using CM.Shared.Entities;
    using CM.DAL.EntityModel;
    public partial class ClientMetaManager : IDataManager
    {
        private FCDB DB;
              
        public ClientMetaManager()
        {
            DB = new FCDB();
        }
    
        /// <summary>
        /// Adds an ClientMeta object to the DbSet of ClientMetas
        /// </summary>
        /// <typeparam name="ClientMeta">The ClientMeta to be added.</param>
        protected virtual void _Add(ClientMeta obj) {
    
                DB.ClientMetas.Add(obj); 
                DB.SaveChanges();
            
        }
    
        /// <summary>
        /// Updates an ClientMeta object to the DbSet of ClientMetas
        /// </summary>
        /// <typeparam name="ClientMeta">The ClientMeta to be updated.</param>
        protected virtual void _Update(ClientMeta obj) {
    
                DB.Entry<ClientMeta>(obj).State = EntityState.Modified;
                DB.SaveChanges();
            
        }
        
        /// <summary>
        /// Deletes an ClientMeta object to the DbSet of ClientMetas
        /// </summary>
        /// <typeparam name="ClientMeta">The ClientMeta to be deleted.</param>
        protected virtual void _Delete(ClientMeta obj) {
    
                DB.Entry<ClientMeta>(obj).State = EntityState.Deleted;
                DB.SaveChanges();
            
        }
        
        /// <summary>
        /// Get an list of ClientMetas
        /// </summary>
        /// <returns>List of ClientMetas</returns>
        protected virtual IEnumerable<ClientMeta> _GetList() {
            return DB.ClientMetas.Select(s=>s);
        }
    
        /// <summary>
        /// Detaches an ClientMeta object from the object state manager.
        /// </summary>
        /// <typeparam name="ClientMeta">The ClientMeta to be detached.</param>
        public virtual void Detach(Object obj) 
    	{
            DB.Entry<ClientMeta>((ClientMeta)obj).State = EntityState.Detached;
            DB.SaveChanges();   
        }
        
        /// <summary>
        /// Adds an ClientMeta object to the DbSet of ClientMetas
        /// </summary>
        /// <typeparam name="ClientMeta">The ClientMeta to be added.</param>
        public virtual void Add(Object obj) 
    	{
            _Add((ClientMeta)obj);
        }
    
        /// <summary>
        /// Updates an ClientMeta object to the DbSet of ClientMetas
        /// </summary>
        /// <typeparam name="ClientMeta">The ClientMeta to be updated.</param>
        public virtual void Update(Object obj) 
    	{
            _Update((ClientMeta)obj);
        }
        
        /// <summary>
        /// Deletes an ClientMeta object to the DbSet of ClientMetas
        /// </summary>
        /// <typeparam name="ClientMeta">The ClientMeta to be deleted.</param>
        public virtual void Delete(Object obj) 
    	{
            _Delete((ClientMeta)obj);
        }
        
        /// <summary>
        /// Get an list of ClientMetas
        /// </summary>
        /// <returns>List of ClientMetas</returns>
        public virtual IEnumerable<ClientMeta> GetList() 
    	{
            return _GetList();
        }
        
    
        /// <summary>
        /// Gets single an ClientMeta object by an key object, key property is (ClientID)
        /// </summary>
        /// <typeparam name="ClientMeta">The ClientMeta to be added.</param>
        /// <returns>An single ClientMeta object</returns>
        public virtual ClientMeta GetByClientID(System.Guid clientid) 
    	{
            if(DB.ClientMetas.Select(s=>s).Where(w=>w.ClientID == clientid).Any()) 
    		{
                return DB.ClientMetas.Select(s=>s).Where(w=>w.ClientID == clientid).FirstOrDefault();
            } else {
                return null;
            }
        }
    
                    
    }
}
