//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CM.DAL.DataManager
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Data.Entity;
    using System.Linq;
    using CM.Interfaces;
    using CM.Shared.Entities;
    using CM.DAL.EntityModel;
    public partial class Client : ClientMetaManager : IDataManager
    {
        private FCDB DB;
              
        public ClientManager()
        {
            DB = new FCDB();
        }
    
        /// <summary>
        /// Adds an Client object to the DbSet of Clients
        /// </summary>
        /// <typeparam name="Client">The Client to be added.</param>
        protected virtual void _Add(Client obj) {
    
                DB.Clients.Add(obj); 
                DB.SaveChanges();
            
        }
    
        /// <summary>
        /// Updates an Client object to the DbSet of Clients
        /// </summary>
        /// <typeparam name="Client">The Client to be updated.</param>
        protected virtual void _Update(Client obj) {
    
                DB.Entry<Client>(obj).State = EntityState.Modified;
                DB.SaveChanges();
            
        }
        
        /// <summary>
        /// Deletes an Client object to the DbSet of Clients
        /// </summary>
        /// <typeparam name="Client">The Client to be deleted.</param>
        protected virtual void _Delete(Client obj) {
    
                DB.Entry<Client>(obj).State = EntityState.Deleted;
                DB.SaveChanges();
            
        }
        
        /// <summary>
        /// Get an list of Clients
        /// </summary>
        /// <returns>List of Clients</returns>
        protected virtual IEnumerable<Client> _GetList() {
            return DB.Clients.Select(s=>s);
        }
    
        /// <summary>
        /// Detaches an Client object from the object state manager.
        /// </summary>
        /// <typeparam name="Client">The Client to be detached.</param>
        public virtual void Detach(Object obj) 
    	{
            DB.Entry<Client>((Client)obj).State = EntityState.Detached;
            DB.SaveChanges();   
        }
        
        /// <summary>
        /// Adds an Client object to the DbSet of Clients
        /// </summary>
        /// <typeparam name="Client">The Client to be added.</param>
        public virtual void Add(Object obj) 
    	{
            _Add((Client)obj);
        }
    
        /// <summary>
        /// Updates an Client object to the DbSet of Clients
        /// </summary>
        /// <typeparam name="Client">The Client to be updated.</param>
        public virtual void Update(Object obj) 
    	{
            _Update((Client)obj);
        }
        
        /// <summary>
        /// Deletes an Client object to the DbSet of Clients
        /// </summary>
        /// <typeparam name="Client">The Client to be deleted.</param>
        public virtual void Delete(Object obj) 
    	{
            _Delete((Client)obj);
        }
        
        /// <summary>
        /// Get an list of Clients
        /// </summary>
        /// <returns>List of Clients</returns>
        public virtual IEnumerable<Client> GetList() 
    	{
            return _GetList();
        }
        
    
    }
}
