//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CM.DAL.DataManager
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Data.Entity;
    using System.Linq;
    using CM.Interfaces;
    using CM.Shared.Entities;
    using CM.DAL.EntityModel;
    public partial class LocationMetaManager : IDataManager
    {
        private FCDB DB;
              
        public LocationMetaManager()
        {
            DB = new FCDB();
        }
    
        /// <summary>
        /// Adds an LocationMeta object to the DbSet of LocationMetas
        /// </summary>
        /// <typeparam name="LocationMeta">The LocationMeta to be added.</param>
        protected virtual void _Add(LocationMeta obj) {
    
                DB.LocationMetas.Add(obj); 
                DB.SaveChanges();
            
        }
    
        /// <summary>
        /// Updates an LocationMeta object to the DbSet of LocationMetas
        /// </summary>
        /// <typeparam name="LocationMeta">The LocationMeta to be updated.</param>
        protected virtual void _Update(LocationMeta obj) {
    
                DB.Entry<LocationMeta>(obj).State = EntityState.Modified;
                DB.SaveChanges();
            
        }
        
        /// <summary>
        /// Deletes an LocationMeta object to the DbSet of LocationMetas
        /// </summary>
        /// <typeparam name="LocationMeta">The LocationMeta to be deleted.</param>
        protected virtual void _Delete(LocationMeta obj) {
    
                DB.Entry<LocationMeta>(obj).State = EntityState.Deleted;
                DB.SaveChanges();
            
        }
        
        /// <summary>
        /// Get an list of LocationMetas
        /// </summary>
        /// <returns>List of LocationMetas</returns>
        protected virtual IEnumerable<LocationMeta> _GetList() {
            return DB.LocationMetas.Select(s=>s);
        }
    
        /// <summary>
        /// Detaches an LocationMeta object from the object state manager.
        /// </summary>
        /// <typeparam name="LocationMeta">The LocationMeta to be detached.</param>
        public virtual void Detach(Object obj) 
    	{
            DB.Entry<LocationMeta>((LocationMeta)obj).State = EntityState.Detached;
            DB.SaveChanges();   
        }
        
        /// <summary>
        /// Adds an LocationMeta object to the DbSet of LocationMetas
        /// </summary>
        /// <typeparam name="LocationMeta">The LocationMeta to be added.</param>
        public virtual void Add(Object obj) 
    	{
            _Add((LocationMeta)obj);
        }
    
        /// <summary>
        /// Updates an LocationMeta object to the DbSet of LocationMetas
        /// </summary>
        /// <typeparam name="LocationMeta">The LocationMeta to be updated.</param>
        public virtual void Update(Object obj) 
    	{
            _Update((LocationMeta)obj);
        }
        
        /// <summary>
        /// Deletes an LocationMeta object to the DbSet of LocationMetas
        /// </summary>
        /// <typeparam name="LocationMeta">The LocationMeta to be deleted.</param>
        public virtual void Delete(Object obj) 
    	{
            _Delete((LocationMeta)obj);
        }
        
        /// <summary>
        /// Get an list of LocationMetas
        /// </summary>
        /// <returns>List of LocationMetas</returns>
        public virtual IEnumerable<LocationMeta> GetList() 
    	{
            return _GetList();
        }
        
    
        /// <summary>
        /// Gets single an LocationMeta object by an key object, key property is (LocationID)
        /// </summary>
        /// <typeparam name="LocationMeta">The LocationMeta to be added.</param>
        /// <returns>An single LocationMeta object</returns>
        public virtual LocationMeta GetByLocationID(System.Guid locationid) 
    	{
            if(DB.LocationMetas.Select(s=>s).Where(w=>w.LocationID == locationid).Any()) 
    		{
                return DB.LocationMetas.Select(s=>s).Where(w=>w.LocationID == locationid).FirstOrDefault();
            } else {
                return null;
            }
        }
    
                    
    }
}
