//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CM.DAL.DataManager
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Data.Entity;
    using System.Linq;
    using CM.Interfaces;
    using CM.Shared.Entities;
    using CM.DAL.EntityModel;
    public partial class LocationTypeMetaManager : IDataManager
    {
        private FCDB DB;
              
        public LocationTypeMetaManager()
        {
            DB = new FCDB();
        }
    
        /// <summary>
        /// Adds an LocationTypeMeta object to the DbSet of LocationTypeMetas
        /// </summary>
        /// <typeparam name="LocationTypeMeta">The LocationTypeMeta to be added.</param>
        protected virtual void _Add(LocationTypeMeta obj) {
    
                DB.LocationTypeMetas.Add(obj); 
                DB.SaveChanges();
            
        }
    
        /// <summary>
        /// Updates an LocationTypeMeta object to the DbSet of LocationTypeMetas
        /// </summary>
        /// <typeparam name="LocationTypeMeta">The LocationTypeMeta to be updated.</param>
        protected virtual void _Update(LocationTypeMeta obj) {
    
                DB.Entry<LocationTypeMeta>(obj).State = EntityState.Modified;
                DB.SaveChanges();
            
        }
        
        /// <summary>
        /// Deletes an LocationTypeMeta object to the DbSet of LocationTypeMetas
        /// </summary>
        /// <typeparam name="LocationTypeMeta">The LocationTypeMeta to be deleted.</param>
        protected virtual void _Delete(LocationTypeMeta obj) {
    
                DB.Entry<LocationTypeMeta>(obj).State = EntityState.Deleted;
                DB.SaveChanges();
            
        }
        
        /// <summary>
        /// Get an list of LocationTypeMetas
        /// </summary>
        /// <returns>List of LocationTypeMetas</returns>
        protected virtual IEnumerable<LocationTypeMeta> _GetList() {
            return DB.LocationTypeMetas.Select(s=>s);
        }
    
        /// <summary>
        /// Detaches an LocationTypeMeta object from the object state manager.
        /// </summary>
        /// <typeparam name="LocationTypeMeta">The LocationTypeMeta to be detached.</param>
        public virtual void Detach(Object obj) 
    	{
            DB.Entry<LocationTypeMeta>((LocationTypeMeta)obj).State = EntityState.Detached;
            DB.SaveChanges();   
        }
        
        /// <summary>
        /// Adds an LocationTypeMeta object to the DbSet of LocationTypeMetas
        /// </summary>
        /// <typeparam name="LocationTypeMeta">The LocationTypeMeta to be added.</param>
        public virtual void Add(Object obj) 
    	{
            _Add((LocationTypeMeta)obj);
        }
    
        /// <summary>
        /// Updates an LocationTypeMeta object to the DbSet of LocationTypeMetas
        /// </summary>
        /// <typeparam name="LocationTypeMeta">The LocationTypeMeta to be updated.</param>
        public virtual void Update(Object obj) 
    	{
            _Update((LocationTypeMeta)obj);
        }
        
        /// <summary>
        /// Deletes an LocationTypeMeta object to the DbSet of LocationTypeMetas
        /// </summary>
        /// <typeparam name="LocationTypeMeta">The LocationTypeMeta to be deleted.</param>
        public virtual void Delete(Object obj) 
    	{
            _Delete((LocationTypeMeta)obj);
        }
        
        /// <summary>
        /// Get an list of LocationTypeMetas
        /// </summary>
        /// <returns>List of LocationTypeMetas</returns>
        public virtual IEnumerable<LocationTypeMeta> GetList() 
    	{
            return _GetList();
        }
        
    
        /// <summary>
        /// Gets single an LocationTypeMeta object by an key object, key property is (LocationTypeID)
        /// </summary>
        /// <typeparam name="LocationTypeMeta">The LocationTypeMeta to be added.</param>
        /// <returns>An single LocationTypeMeta object</returns>
        public virtual LocationTypeMeta GetByLocationTypeID(System.Guid locationtypeid) 
    	{
            if(DB.LocationTypeMetas.Select(s=>s).Where(w=>w.LocationTypeID == locationtypeid).Any()) 
    		{
                return DB.LocationTypeMetas.Select(s=>s).Where(w=>w.LocationTypeID == locationtypeid).FirstOrDefault();
            } else {
                return null;
            }
        }
    
                    
    }
}
